// user
export const SET_USER = "SET_USER"
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const LOADING_USER = "LOADING_USER";
export const SET_CONFIRMED_USER = "SET_CONFIRMED_USER";


// UI
export const SET_ERRORS = "SET_ERRORS"
export const LOADING_UI = "LOADING_UI"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const STOP_LOADING_UI = "STOP_LOADING_UI"

// channels
export const LOADING_CHANNELS = "LOADING_CHANNELS";
export const SET_CHANNELS = "SET_CHANNELS";
export const SET_CURRENT_CHANNEL = "SET_CHANNEL";
export const CREATE_CHANNEL = "CREATE_CHANNEL";
export const UPDATE_CHANNEL = "UPDATE_CHANNEL";
export const STOP_LOADING_CHANNELS = "STOP_LOADING_CHANNELS";
export const SUBSCRIBE = "SUBSCRIBE";
export const UNSET_CURRENT_CHANNEL = "UNSET_CHANNEL";

// products 
export const LOADING_PRODUCTS = "LOADING_PRODUCTS"
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT = "SET_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const STOP_LOADING_PRODUCTS = "STOP_LOADING_PRODUCTS";

// reviews and questions
export const SUBMIT_QUESTION = "SUBMIT_QUESTION"
export const DELETE_QUESTION = "DELETE_QUESTION"
export const SUBMIT_REVIEW =  "SUBMIT_REVIEW"
export const DELETE_REVIEW = "DELETE_REVIEW"

// FORM
export const SET_MAIN_INFO = "SET_MAIN_INFO";
export const SET_ADDITIONAL_INFO = "SET_ADDITIONAL_INFO";
export const SET_CREATE_PRODUCT_ERRORS = "SET_CREATE_PRODUCT_ERROR";
export const SET_LOADING_CREATE_PRODUCT = "SET_LOADING_CREATE_PRODUCT";
export const RESET_FORM = "RESET_FORM";